# Generated by Django 5.2.8 on 2025-12-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_create_rename_tittle_listing_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="isAcive",
            new_name="isActive",
        ),
    ]
