# Generated by Django 5.2.8 on 2025-12-23 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_isacive_listing_isactive"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="created_listing",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
