# Generated by Django 5.2.8 on 2025-12-26 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_listing_created_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watch_list",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
